---
- name: Grant database connection
  community.postgresql.postgresql_privs:
    login_db: postgres
    type: database
    objs: "{{ cloudutil_postgres_privilege.db }}"
    privs: CONNECT
    roles: "{{ cloudutil_postgres_role.name }}"
    state: present
    login_host: "{{ cloudutil_postgres.provider.host }}"
    login_port: "{{ cloudutil_postgres.provider.port }}"
    login_user: "{{ cloudutil_postgres.provider.username }}"
    login_password: "{{ cloudutil_postgres.provider.password }}"
    ssl_mode: "{{ cloudutil_postgres.provider.ssl_mode or ('verify-full' if cloudutil_postgres.provider.cert else ('require' if cloudutil_postgres.provider.mtls else 'prefer')) }}"
    ca_cert: "{{ cloudutil_postgres.provider.cert }}"
    ssl_cert: "{{ cloudutil_postgres.provider.mtls.cert if cloudutil_postgres.provider.mtls else omit }}"
    ssl_key: "{{ cloudutil_postgres.provider.mtls.key if cloudutil_postgres.provider.mtls else omit }}"

- name: Grant schema usage
  community.postgresql.postgresql_privs:
    login_db: "{{ cloudutil_postgres_privilege.db }}"
    type: schema
    objs: "{{ cloudutil_postgres_privilege.db_schema }}"
    privs: USAGE
    roles: "{{ cloudutil_postgres_role.name }}"
    state: present
    login_host: "{{ cloudutil_postgres.provider.host }}"
    login_port: "{{ cloudutil_postgres.provider.port }}"
    login_user: "{{ cloudutil_postgres.provider.username }}"
    login_password: "{{ cloudutil_postgres.provider.password }}"
    ssl_mode: "{{ cloudutil_postgres.provider.ssl_mode or ('verify-full' if cloudutil_postgres.provider.cert else ('require' if cloudutil_postgres.provider.mtls else 'prefer')) }}"
    ca_cert: "{{ cloudutil_postgres.provider.cert }}"
    ssl_cert: "{{ cloudutil_postgres.provider.mtls.cert if cloudutil_postgres.provider.mtls else omit }}"
    ssl_key: "{{ cloudutil_postgres.provider.mtls.key if cloudutil_postgres.provider.mtls else omit }}"

- name: Grant schema creation to read/write roles
  community.postgresql.postgresql_privs:
    login_db: "{{ cloudutil_postgres_privilege.db }}"
    type: schema
    objs: "{{ cloudutil_postgres_privilege.db_schema }}"
    privs: CREATE
    roles: "{{ cloudutil_postgres_role.name }}"
    state: present
    login_host: "{{ cloudutil_postgres.provider.host }}"
    login_port: "{{ cloudutil_postgres.provider.port }}"
    login_user: "{{ cloudutil_postgres.provider.username }}"
    login_password: "{{ cloudutil_postgres.provider.password }}"
    ssl_mode: "{{ cloudutil_postgres.provider.ssl_mode or ('verify-full' if cloudutil_postgres.provider.cert else ('require' if cloudutil_postgres.provider.mtls else 'prefer')) }}"
    ca_cert: "{{ cloudutil_postgres.provider.cert }}"
    ssl_cert: "{{ cloudutil_postgres.provider.mtls.cert if cloudutil_postgres.provider.mtls else omit }}"
    ssl_key: "{{ cloudutil_postgres.provider.mtls.key if cloudutil_postgres.provider.mtls else omit }}"
  when: cloudutil_postgres_privilege.readwrite

- name: Grant privileges on all current tables
  community.postgresql.postgresql_privs:
    login_db: "{{ cloudutil_postgres_privilege.db }}"
    type: table
    objs: ALL_IN_SCHEMA
    schema: "{{ cloudutil_postgres_privilege.db_schema }}"
    privs: "{{ 'SELECT,INSERT,UPDATE,DELETE' if cloudutil_postgres_privilege.readwrite else 'SELECT' }}"
    roles: "{{ cloudutil_postgres_role.name }}"
    state: present
    login_host: "{{ cloudutil_postgres.provider.host }}"
    login_port: "{{ cloudutil_postgres.provider.port }}"
    login_user: "{{ cloudutil_postgres.provider.username }}"
    login_password: "{{ cloudutil_postgres.provider.password }}"
    ssl_mode: "{{ cloudutil_postgres.provider.ssl_mode or ('verify-full' if cloudutil_postgres.provider.cert else ('require' if cloudutil_postgres.provider.mtls else 'prefer')) }}"
    ca_cert: "{{ cloudutil_postgres.provider.cert }}"
    ssl_cert: "{{ cloudutil_postgres.provider.mtls.cert if cloudutil_postgres.provider.mtls else omit }}"
    ssl_key: "{{ cloudutil_postgres.provider.mtls.key if cloudutil_postgres.provider.mtls else omit }}"
  when: "'ALL' in cloudutil_postgres_privilege.tables"

- name: Grant privileges on future tables
  community.postgresql.postgresql_privs:
    login_db: "{{ cloudutil_postgres_privilege.db }}"
    type: default_privs
    objs: TABLES
    schema: "{{ cloudutil_postgres_privilege.db_schema }}"
    privs: "{{ 'SELECT,INSERT,UPDATE,DELETE' if cloudutil_postgres_privilege.readwrite else 'SELECT' }}"
    roles: "{{ cloudutil_postgres_role.name }}"
    state: present
    login_host: "{{ cloudutil_postgres.provider.host }}"
    login_port: "{{ cloudutil_postgres.provider.port }}"
    login_user: "{{ cloudutil_postgres.provider.username }}"
    login_password: "{{ cloudutil_postgres.provider.password }}"
    ssl_mode: "{{ cloudutil_postgres.provider.ssl_mode or ('verify-full' if cloudutil_postgres.provider.cert else ('require' if cloudutil_postgres.provider.mtls else 'prefer')) }}"
    ca_cert: "{{ cloudutil_postgres.provider.cert }}"
    ssl_cert: "{{ cloudutil_postgres.provider.mtls.cert if cloudutil_postgres.provider.mtls else omit }}"
    ssl_key: "{{ cloudutil_postgres.provider.mtls.key if cloudutil_postgres.provider.mtls else omit }}"
  when: "'ALL' in cloudutil_postgres_privilege.tables"

- name: Grant privileges on named tables
  community.postgresql.postgresql_privs:
    login_db: "{{ cloudutil_postgres_privilege.db }}"
    type: table
    objs: "{{ item }}"
    schema: "{{ cloudutil_postgres_privilege.db_schema }}"
    privs: "{{ 'SELECT,INSERT,UPDATE,DELETE' if cloudutil_postgres_privilege.readwrite else 'SELECT' }}"
    roles: "{{ cloudutil_postgres_role.name }}"
    state: present
    login_host: "{{ cloudutil_postgres.provider.host }}"
    login_port: "{{ cloudutil_postgres.provider.port }}"
    login_user: "{{ cloudutil_postgres.provider.username }}"
    login_password: "{{ cloudutil_postgres.provider.password }}"
    ssl_mode: "{{ cloudutil_postgres.provider.ssl_mode or ('verify-full' if cloudutil_postgres.provider.cert else ('require' if cloudutil_postgres.provider.mtls else 'prefer')) }}"
    ca_cert: "{{ cloudutil_postgres.provider.cert }}"
    ssl_cert: "{{ cloudutil_postgres.provider.mtls.cert if cloudutil_postgres.provider.mtls else omit }}"
    ssl_key: "{{ cloudutil_postgres.provider.mtls.key if cloudutil_postgres.provider.mtls else omit }}"
  loop: "{{ cloudutil_postgres_privilege.tables | reject('equalto', 'ALL') }}"
