global_ignore_keys:
  - metadata
  - status

global_ignore_patterns:
  - dev
  - TEST

diffs:
  - files:
      - examples/prod.yaml
      - examples/stage.yaml

    ignore_keys:
      - data

  - files:
      - examples/service-a.toml
      - examples/service-b.toml
